import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting NIMBLUX database seed...");

  // Clean existing data
  await prisma.report.deleteMany({});
  await prisma.notification.deleteMany({});
  await prisma.bookmark.deleteMany({});
  await prisma.opportunity.deleteMany({});
  await prisma.event.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.user.deleteMany({});

  // 1. Create Users
  const adminPassword = await bcrypt.hash("8937Dev@Nimblux", 10);
  const studentPassword = await bcrypt.hash("Student@123", 10);

  const admin = await prisma.user.create({
    data: {
      name: "NIMBLUX Admin",
      email: "admin@nimblux.com",
      passwordHash: adminPassword,
      role: "ADMIN",
      profileImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      location: "San Francisco, CA",
      bio: "Chief Platform Moderator & Tech Lead at NIMBLUX.",
      status: "ACTIVE",
    },
  });

  const student = await prisma.user.create({
    data: {
      name: "Alex Rivera",
      email: "student@nimblux.com",
      passwordHash: studentPassword,
      role: "USER",
      profileImage: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
      college: "Stanford University",
      degree: "B.S. Computer Science & AI",
      skills: "TypeScript, Python, React, Next.js, PyTorch, GraphQL",
      graduationYear: "2026",
      location: "San Francisco, CA",
      bio: "Passionate CS undergrad exploring full-stack engineering, distributed systems, and modern AI pipelines.",
      githubUrl: "https://github.com",
      linkedinUrl: "https://linkedin.com",
      status: "ACTIVE",
    },
  });

  const student2 = await prisma.user.create({
    data: {
      name: "Priya Sharma",
      email: "priya.sharma@nimblux.com",
      passwordHash: studentPassword,
      role: "USER",
      profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      college: "IIT Bombay",
      degree: "B.Tech Computer Science",
      skills: "Rust, Go, Kubernetes, Cloud Architecture, Docker",
      graduationYear: "2026",
      location: "Mumbai, India",
      bio: "Systems hacker and cloud native enthusiast. Active open-source contributor.",
      githubUrl: "https://github.com",
      linkedinUrl: "https://linkedin.com",
      status: "ACTIVE",
    },
  });

  console.log("👤 Created users (Admin & Students)");

  // 2. Create Categories
  const categoriesData = [
    { name: "Internships", slug: "internships", icon: "Briefcase", description: "Top software engineering, AI, product & design internships.", displayOrder: 1 },
    { name: "Hackathons", slug: "hackathons", icon: "Code", description: "Global hackathons with prizes, mentorship, and VC backing.", displayOrder: 2 },
    { name: "Jobs", slug: "jobs", icon: "Building2", description: "Graduate, new-grad, and junior developer roles.", displayOrder: 3 },
    { name: "Events", slug: "events", icon: "Calendar", description: "Tech meetups, developer conferences, and summits.", displayOrder: 4 },
    { name: "Competitions", slug: "competitions", icon: "Trophy", description: "Competitive coding, algorithmic battles, and innovation challenges.", displayOrder: 5 },
    { name: "Scholarships", slug: "scholarships", icon: "GraduationCap", description: "Tech fellowships, university grants, and research funding.", displayOrder: 6 },
    { name: "Workshops", slug: "workshops", icon: "Sparkles", description: "Interactive hands-on technical masterclasses.", displayOrder: 7 },
    { name: "Courses", slug: "courses", icon: "BookOpen", description: "Certified engineering courses from industry leaders.", displayOrder: 8 },
    { name: "Fellowships", slug: "fellowships", icon: "Award", description: "Elite developer cohorts and founder accelerator fellowships.", displayOrder: 9 },
    { name: "Conferences", slug: "conferences", icon: "Mic2", description: "International tech summits and keynotes.", displayOrder: 10 },
    { name: "Webinars", slug: "webinars", icon: "Video", description: "Live tech deep dives and AMAs with industry leaders.", displayOrder: 11 },
    { name: "Volunteering", slug: "volunteering", icon: "HeartHandshake", description: "Community initiatives and open-source contributions.", displayOrder: 12 },
    { name: "Campus Opportunities", slug: "campus-opportunities", icon: "School", description: "Campus ambassador and student leader roles.", displayOrder: 13 },
    { name: "Other", slug: "other", icon: "Compass", description: "Startup grants, venture cohorts, and specialty programs.", displayOrder: 14 },
  ];

  for (const cat of categoriesData) {
    await prisma.category.create({ data: cat });
  }

  console.log("📂 Created 14 Categories");

  // 3. Create High-Quality Opportunities
  const opportunities = [
    {
      title: "Google Summer Software Engineering Internship 2026",
      slug: "google-summer-software-engineering-internship-2026",
      description: "Join Google as a Software Engineering Intern! Work on core infrastructure, developer tools, Gemini AI integrations, and cloud scale systems. You will collaborate with experienced engineers and solve complex algorithmic problems while impacting billions of global users.\n\nKey Responsibilities:\n• Design, develop, test, deploy, maintain and improve software.\n• Manage individual project priorities, deadlines and deliverables.\n• Collaborate with cross-functional teams across engineering, research, and design.",
      category: "internships",
      organization: "Google",
      logo: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80",
      location: "Mountain View, CA / Hybrid",
      mode: "HYBRID",
      eligibility: "Currently pursuing a Bachelor's, Master's or PhD in Computer Science, Software Engineering, or related technical field graduating in 2026 or 2027.",
      skills: "C++, Java, Python, Go, Data Structures, Algorithms, Distributed Systems",
      stipend: "$9,200 / month + Housing Allowance",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://careers.google.com/students",
      deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000), // 35 days from now
      startDate: new Date("2026-06-01"),
      endDate: new Date("2026-08-28"),
      contactInfo: "university-programs@google.com",
      additionalInfo: "Includes weekly 1:1 mentorship, intern tech summits, and full-time return offer consideration.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 1420,
      viewsCount: 5200,
      createdById: student.id,
      approvedById: admin.id,
    },
    {
      title: "Microsoft Imagine Cup Global Hackathon 2026",
      slug: "microsoft-imagine-cup-global-hackathon-2026",
      description: "The Imagine Cup is Microsoft's premier global student technology and entrepreneurship competition. Build groundbreaking applications leveraging Azure OpenAI, GitHub Copilot, and cloud technologies to solve critical world challenges. Win $100,000 USD, a 1:1 mentorship session with Microsoft Chairman and CEO Satya Nadella, and global media recognition.",
      category: "hackathons",
      organization: "Microsoft",
      logo: "https://images.unsplash.com/photo-1642132652806-9430c4c4ea3b?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80",
      location: "Global / Online + Redmond Finals",
      mode: "REMOTE",
      eligibility: "Students aged 16+ enrolled in accredited educational institutions worldwide. Teams of 1 to 4 members.",
      skills: "Cloud Architecture, AI/ML, React, Node.js, Python, UI/UX, Innovation",
      stipend: "$100,000 Grand Prize + $50k Azure Credits",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://imaginecup.microsoft.com",
      deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
      contactInfo: "imaginecup@microsoft.com",
      additionalInfo: "Top 3 teams flown to Microsoft HQ in Redmond for the live World Finals.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 2310,
      viewsCount: 8400,
      createdById: admin.id,
      approvedById: admin.id,
    },
    {
      title: "ETHIndia 2026 - Asia's Premier Web3 & Protocol Hackathon",
      slug: "ethindia-2026-asias-premier-web3-hackathon",
      description: "ETHIndia brings together 2,000+ top builders, protocol engineers, founders, and students for 36 hours of non-stop hacking. Build decentralized applications, zero-knowledge proofs, account abstraction tooling, and decentralized AI infra with mentors from Ethereum Foundation, Polygon, Optimism, and Arbitrum.",
      category: "hackathons",
      organization: "ETHIndia & Devfolio",
      logo: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80",
      location: "Bengaluru, India",
      mode: "ONSITE",
      eligibility: "Open to all developers, designers, and web3 enthusiasts. Beginners are welcome with dedicated tracks.",
      skills: "Solidity, Rust, TypeScript, Smart Contracts, ZK-Snarks, Web3.js, Ethers.js",
      stipend: "$150,000+ Prize Pool + Travel Grants",
      salary: null,
      registrationFee: "Free (Includes Accommodation & Food)",
      isPaid: true,
      applicationUrl: "https://ethindia.co",
      deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 32 * 24 * 60 * 60 * 1000),
      contactInfo: "hello@ethindia.co",
      additionalInfo: "Travel scholarships available for selected student hackers outside Karnataka.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 3100,
      viewsCount: 9800,
      createdById: student2.id,
      approvedById: admin.id,
    },
    {
      title: "Amazon Graduate Software Development Engineer (SDE-1)",
      slug: "amazon-graduate-software-development-engineer-sde1",
      description: "Amazon is hiring full-time entry-level Software Development Engineers (SDE-1) across AWS, Prime Video, Alexa, and Core Retail engineering. As an SDE-1, you will write scalable production services, build high-throughput microservices, and influence architecture decisions for services handling millions of requests per second.",
      category: "jobs",
      organization: "Amazon / AWS",
      logo: "https://images.unsplash.com/photo-1523474255658-40e4509cc013?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop&q=80",
      location: "Seattle, WA / Austin, TX / Remote Option",
      mode: "HYBRID",
      eligibility: "Graduating with a Bachelor's or Master's in CS/ECE/IT between Dec 2025 and Aug 2026.",
      skills: "Java, Python, C++, AWS, Distributed Architecture, System Design, REST APIs",
      stipend: null,
      salary: "$145,000 - $175,000 / year + Sign-on + RSUs",
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://amazon.jobs/en/student-programs",
      deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
      startDate: new Date("2026-07-15"),
      endDate: null,
      contactInfo: "aws-university-recruiting@amazon.com",
      additionalInfo: "Relocation bonus and comprehensive healthcare benefits included.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 1890,
      viewsCount: 6300,
      createdById: student.id,
      approvedById: admin.id,
    },
    {
      title: "Goldman Sachs Engineering Campus Hiring & Internship Program",
      slug: "goldman-sachs-engineering-campus-hiring-program",
      description: "The Goldman Sachs Engineering Campus Hiring Program is designed to identify and recruit the next generation of technologists. Interns work directly on real-time financial modeling engines, algorithmic trading frameworks, cloud security infrastructure, and AI analytics.",
      category: "internships",
      organization: "Goldman Sachs",
      logo: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80",
      location: "New York, NY / Bengaluru, India",
      mode: "HYBRID",
      eligibility: "Undergraduate and master's students pursuing technical degrees. Minimum 7.5 CGPA or equivalent.",
      skills: "Java, C++, Python, Data Structures, Algorithms, SQL, Quantitative Modeling",
      stipend: "$8,500 / month ($100k INR / month in India)",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://www.goldmansachs.com/careers/students",
      deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
      startDate: new Date("2026-05-20"),
      endDate: new Date("2026-07-31"),
      contactInfo: "campusrecruiting@gs.com",
      additionalInfo: "Fast-track pre-placement interviews for top 10% performers.",
      status: "APPROVED",
      featured: false,
      verified: true,
      clicksCount: 980,
      viewsCount: 3400,
      createdById: student.id,
      approvedById: admin.id,
    },
    {
      title: "MITACS Globalink Research Internship & Fellowship 2026",
      slug: "mitacs-globalink-research-internship-scholarship-2026",
      description: "Fully-funded 12-week research internship at top Canadian universities (University of Toronto, UBC, McGill, Waterloo). Work with world-class faculty on cutting-edge research in quantum computing, generative AI, robotics, and biomedical engineering.",
      category: "scholarships",
      organization: "Mitacs Canada & Government of Canada",
      logo: "https://images.unsplash.com/photo-1532619675605-1ede6c2ed2b0?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&auto=format&fit=crop&q=80",
      location: "Canada (Various Universities)",
      mode: "ONSITE",
      eligibility: "Full-time enrolled undergraduate students with at least 1-3 semesters remaining. Minimum 8.0 CGPA.",
      skills: "Scientific Research, Python, C++, Data Analysis, Machine Learning, Academic Writing",
      stipend: "$10,000 CAD (Flight, Housing, Stipend Included)",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://www.mitacs.ca/our-programs/globalink-research-internship-students/",
      deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
      startDate: new Date("2026-05-15"),
      endDate: new Date("2026-08-15"),
      contactInfo: "globalink@mitacs.ca",
      additionalInfo: "Qualifies candidates for the Mitacs Globalink Graduate Fellowship for Canadian Master's/PhD funding.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 1650,
      viewsCount: 4700,
      createdById: admin.id,
      approvedById: admin.id,
    },
    {
      title: "OpenAI Frontier AI Fellowship & Research Grant 2026",
      slug: "openai-frontier-ai-fellowship-research-grant-2026",
      description: "A 6-month intensive research fellowship at OpenAI. Collaborate directly with world-class research scientists and safety researchers to advance foundational reasoning models, multimodal agent architectures, and AI alignment mechanisms.",
      category: "fellowships",
      organization: "OpenAI",
      logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&auto=format&fit=crop&q=80",
      location: "San Francisco, CA / Hybrid",
      mode: "HYBRID",
      eligibility: "Exceptional undergraduate, master's or independent researchers with demonstrated publications or open-source machine learning repos.",
      skills: "PyTorch, CUDA, Transformers, RLHF, Large Language Models, Distributed GPU Training",
      stipend: "$15,000 / month + Compute Grant ($50k)",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://openai.com/careers/fellowships",
      deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
      startDate: new Date("2026-07-01"),
      endDate: new Date("2026-12-31"),
      contactInfo: "fellowships@openai.com",
      additionalInfo: "Access to thousands of NVIDIA H100/B200 clusters for independent research publications.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 4200,
      viewsCount: 12000,
      createdById: admin.id,
      approvedById: admin.id,
    },
    {
      title: "NVIDIA Deep Learning & GPU Acceleration Workshop 2026",
      slug: "nvidia-deep-learning-gpu-acceleration-workshop-2026",
      description: "Hands-on virtual technical workshop by NVIDIA Deep Learning Institute (DLI). Learn TensorRT optimization, CUDA kernel programming, and deploying LLMs on edge devices with RTX and Jetson chips. Certificate of Competency awarded upon completion.",
      category: "workshops",
      organization: "NVIDIA DLI",
      logo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80",
      location: "Online / Virtual Lab",
      mode: "REMOTE",
      eligibility: "Open to all software developers and AI practitioners with intermediate Python knowledge.",
      skills: "CUDA, TensorRT, PyTorch, GPU Optimization, Deep Learning Inference",
      stipend: "NVIDIA DLI Official Certificate ($500 value free for students)",
      salary: null,
      registrationFee: "Free for Students",
      isPaid: false,
      applicationUrl: "https://www.nvidia.com/en-us/training/",
      deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000),
      contactInfo: "dli-workshops@nvidia.com",
      additionalInfo: "Includes 8 hours of dedicated cloud GPU lab time.",
      status: "APPROVED",
      featured: false,
      verified: true,
      clicksCount: 840,
      viewsCount: 2900,
      createdById: student2.id,
      approvedById: admin.id,
    },
    {
      title: "React Universe & Next.js Global Conference 2026",
      slug: "react-universe-and-nextjs-global-conference-2026",
      description: "The world's flagship gathering for React, Next.js, and modern full-stack web architects. Featuring keynotes on React Server Components, Turbopack, AI SDKs, and Edge computing with creators and core maintainers.",
      category: "conferences",
      organization: "Vercel & Callstack",
      logo: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80",
      location: "Wroclaw, Poland + Global Live Stream",
      mode: "REMOTE",
      eligibility: "Open to developers and students worldwide. Free virtual streaming tickets available.",
      skills: "React, Next.js, TypeScript, Server Components, Web Vitals, Edge APIs",
      stipend: null,
      salary: null,
      registrationFee: "Free Virtual Pass / Student Pass Available",
      isPaid: false,
      applicationUrl: "https://reactuniverseconf.com",
      deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 50 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 52 * 24 * 60 * 60 * 1000),
      contactInfo: "events@reactuniverse.com",
      additionalInfo: "Virtual attendees get access to workshop recordings and private Discord channel.",
      status: "APPROVED",
      featured: false,
      verified: true,
      clicksCount: 720,
      viewsCount: 2400,
      createdById: admin.id,
      approvedById: admin.id,
    },
    {
      title: "GitHub Campus Expert & Student Ambassador 2026",
      slug: "github-campus-expert-student-ambassador-2026",
      description: "Become the voice of developer education on your university campus! GitHub Campus Experts are student leaders who build technology communities, organize hackathons, teach Git/GitHub, and receive swag, event funding, and direct mentorship from GitHub staff.",
      category: "campus-opportunities",
      organization: "GitHub Education",
      logo: "https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&auto=format&fit=crop&q=80",
      location: "Worldwide (Your Campus)",
      mode: "REMOTE",
      eligibility: "Enrolled in college/university with at least 1 year of study remaining. Passionate about community building.",
      skills: "Public Speaking, Git, Community Leadership, Event Management, Workshop Hosting",
      stipend: "$1,000 Event Budget Grants + GitHub Exclusive Gear",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://education.github.com/experts",
      deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
      startDate: new Date("2026-06-01"),
      endDate: new Date("2027-06-01"),
      contactInfo: "education@github.com",
      additionalInfo: "Graduates are fast-tracked for GitHub internships and full-time hiring.",
      status: "APPROVED",
      featured: true,
      verified: true,
      clicksCount: 1540,
      viewsCount: 4600,
      createdById: student2.id,
      approvedById: admin.id,
    },
    {
      title: "Harvard Crimson Collegiate Innovation & Coding Cup",
      slug: "harvard-crimson-collegiate-coding-cup-2026",
      description: "Prestigious annual collegiate coding tournament with algorithmic challenges, system design rounds, and a venture pitch finale evaluated by Silicon Valley VCs and Harvard CS faculty.",
      category: "competitions",
      organization: "Harvard CS Society",
      logo: "https://images.unsplash.com/photo-1562774053-701939374585?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&auto=format&fit=crop&q=80",
      location: "Cambridge, MA / Hybrid",
      mode: "HYBRID",
      eligibility: "Undergraduates and graduate students worldwide. Solos or teams of 2.",
      skills: "Algorithms, Dynamic Programming, System Design, Pitch Deck, C++, Python",
      stipend: "$30,000 in Prizes & VC Term Sheet Consideration",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://harvardcs.org/competition",
      deadline: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000),
      contactInfo: "compete@harvardcs.org",
      additionalInfo: "Top 10 finalists present live in Sanders Theatre at Harvard University.",
      status: "APPROVED",
      featured: false,
      verified: true,
      clicksCount: 890,
      viewsCount: 3100,
      createdById: student.id,
      approvedById: admin.id,
    },
    {
      title: "Full-Stack AI Engineering Specialization Cohort",
      slug: "full-stack-ai-engineering-specialization-cohort-2026",
      description: "Intensive 10-week certified online course on building production AI applications using Next.js 14, LangChain, LlamaIndex, Vector DBs (Pinecone/Qdrant), and fine-tuned open-source models.",
      category: "courses",
      organization: "DeepLearning.AI & NIMBLUX Academy",
      logo: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=1200&auto=format&fit=crop&q=80",
      location: "Online / Self-Paced + Live Office Hours",
      mode: "REMOTE",
      eligibility: "Open to anyone with foundational JavaScript or Python experience.",
      skills: "Next.js, LangChain, RAG Systems, Vector Databases, OpenAI API, FastAPI",
      stipend: "100% Scholarship Available for Students",
      salary: null,
      registrationFee: "Free for first 500 students",
      isPaid: false,
      applicationUrl: "https://learn.nimblux.com/ai-engineering",
      deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 86 * 24 * 60 * 60 * 1000),
      contactInfo: "academy@nimblux.com",
      additionalInfo: "Verified badge and GitHub repo portfolio projects provided upon graduation.",
      status: "APPROVED",
      featured: false,
      verified: true,
      clicksCount: 1120,
      viewsCount: 3900,
      createdById: admin.id,
      approvedById: admin.id,
    },

    // --- PENDING SUBMISSIONS (To demonstrate moderation queue in Admin dashboard) ---
    {
      title: "Stripe New Grad Infrastructure Engineer 2026",
      slug: "stripe-new-grad-infrastructure-engineer-2026",
      description: "Join Stripe's Infrastructure Engineering organization to design and operate global payments systems that move hundreds of billions of dollars annually. Build fault-tolerant distributed databases and high-availability APIs.",
      category: "jobs",
      organization: "Stripe",
      logo: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80",
      location: "San Francisco, CA / Dublin / Remote",
      mode: "HYBRID",
      eligibility: "Graduating class of 2026 with Bachelor's or Master's in Computer Science.",
      skills: "Go, Ruby, Java, Distributed Systems, Linux, High Concurrency, Kubernetes",
      stipend: null,
      salary: "$150,000 - $185,000 / year + Equity",
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://stripe.com/jobs/infrastructure-newgrad",
      deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      startDate: new Date("2026-08-01"),
      endDate: null,
      contactInfo: "university-jobs@stripe.com",
      additionalInfo: "Submitted by Alex Rivera for verification.",
      status: "PENDING", // PENDING APPROVAL
      rejectionReason: null,
      featured: false,
      verified: false,
      clicksCount: 0,
      viewsCount: 14,
      createdById: student.id,
      approvedById: null,
    },
    {
      title: "Solana Superteam Buildstation Cohort & Hackathon",
      slug: "solana-superteam-buildstation-cohort-2026",
      description: "A 4-week co-working space and hackathon sprint for builders developing high-speed consumer dApps, DeFi protocols, and DePIN projects on Solana. Demo day with global web3 investors.",
      category: "hackathons",
      organization: "Superteam & Solana Foundation",
      logo: "https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=100&auto=format&fit=crop&q=80",
      banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=80",
      location: "Bangalore, India & Remote",
      mode: "HYBRID",
      eligibility: "Open to all web3 developers and student teams.",
      skills: "Rust, Anchor Framework, TypeScript, Web3, Solana Pay",
      stipend: "$50,000 in Grants + Co-working Desk Access",
      salary: null,
      registrationFee: "Free",
      isPaid: true,
      applicationUrl: "https://superteam.fun/buildstation",
      deadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
      startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      endDate: new Date(Date.now() + 38 * 24 * 60 * 60 * 1000),
      contactInfo: "india@superteam.fun",
      additionalInfo: "Awaiting moderator review.",
      status: "PENDING", // PENDING APPROVAL
      rejectionReason: null,
      featured: false,
      verified: false,
      clicksCount: 0,
      viewsCount: 8,
      createdById: student2.id,
      approvedById: null,
    },

    // --- REJECTED SUBMISSION (To demonstrate rejection status + reason in user dashboard) ---
    {
      title: "Crypto Trading Signals Discord Mod & Promoter",
      slug: "crypto-trading-signals-discord-mod-promoter",
      description: "Looking for students to spam Telegram and Discord groups promoting 100x crypto trading signals. Commission based pay.",
      category: "other",
      organization: "Anonymous Crypto Club",
      logo: null,
      banner: null,
      location: "Remote",
      mode: "REMOTE",
      eligibility: "None",
      skills: "Spamming, Social Media",
      stipend: "Commission only",
      salary: null,
      registrationFee: "$20 entry fee",
      isPaid: false,
      applicationUrl: "https://t.me/fake_signals_group",
      deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      startDate: null,
      endDate: null,
      contactInfo: "spammer@fake.com",
      additionalInfo: "Flagged by automated filters.",
      status: "REJECTED",
      rejectionReason: "Policy violation: NIMBLUX prohibits paid promotions, multi-level marketing, paid entry fees for job seekers, and unverified speculative trading groups.",
      featured: false,
      verified: false,
      clicksCount: 0,
      viewsCount: 2,
      createdById: student.id,
      approvedById: admin.id,
    },
  ];

  for (const opp of opportunities) {
    await prisma.opportunity.create({ data: opp });
  }

  console.log(`🚀 Seeded ${opportunities.length} realistic opportunities`);

  // 4. Create NIMBLUX Events
  const events = [
    {
      title: "NIMBLUX Global Tech Summit & Hackathon 2026",
      slug: "nimblux-global-tech-summit-hackathon-2026",
      description: "The flagship annual hackathon and innovation summit hosted by NIMBLUX. Connect with top recruiters from Google, Microsoft, and high-growth YC startups. Build and pitch AI, web3, and cloud projects.",
      banner: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80",
      eventDate: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000),
      location: "Online + San Francisco & Bengaluru Hubs",
      mode: "HYBRID",
      registrationUrl: "https://nimblux.com/events/summit-2026",
      organizer: "NIMBLUX Team",
      isFeatured: true,
    },
    {
      title: "FAANG Tech Interview & System Design Masterclass",
      slug: "faang-tech-interview-system-design-masterclass",
      description: "Live interactive deep dive on cracking coding rounds, behavioral questions, and distributed system design with Staff Software Engineers from Meta and Google.",
      banner: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=1200&auto=format&fit=crop&q=80",
      eventDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
      location: "Virtual (Zoom Interactive Room)",
      mode: "REMOTE",
      registrationUrl: "https://nimblux.com/events/interview-masterclass",
      organizer: "NIMBLUX Community",
      isFeatured: true,
    },
    {
      title: "Open Source Hack Night & GitHub Mentorship",
      slug: "open-source-hack-night-github-mentorship",
      description: "Hands-on guided sprint to make your first meaningful contributions to top open-source repositories and earn verified developer badges.",
      banner: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80",
      eventDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      location: "Virtual Discord Stage",
      mode: "REMOTE",
      registrationUrl: "https://nimblux.com/events/open-source-night",
      organizer: "NIMBLUX Developer Guild",
      isFeatured: false,
    },
  ];

  for (const ev of events) {
    await prisma.event.create({ data: ev });
  }

  console.log(`📅 Created ${events.length} NIMBLUX Events`);

  // 5. Create Bookmarks for Student User
  const googleOpp = await prisma.opportunity.findUnique({
    where: { slug: "google-summer-software-engineering-internship-2026" },
  });
  const imagineCupOpp = await prisma.opportunity.findUnique({
    where: { slug: "microsoft-imagine-cup-global-hackathon-2026" },
  });

  if (googleOpp && imagineCupOpp) {
    await prisma.bookmark.create({
      data: { userId: student.id, opportunityId: googleOpp.id },
    });
    await prisma.bookmark.create({
      data: { userId: student.id, opportunityId: imagineCupOpp.id },
    });
  }

  // 6. Create Notifications for Student
  await prisma.notification.createMany({
    data: [
      {
        userId: student.id,
        title: "Welcome to NIMBLUX! 🎉",
        message: "Your account has been created. Explore thousands of internships, hackathons, and scholarships curated for students.",
        type: "SYSTEM",
        link: "/opportunities",
        isRead: true,
      },
      {
        userId: student.id,
        title: "Opportunity Approved! 🚀",
        message: "Your submission 'Google Summer Software Engineering Internship 2026' was reviewed and published on the live platform.",
        type: "APPROVAL",
        link: "/opportunity/google-summer-software-engineering-internship-2026",
        isRead: false,
      },
      {
        userId: student.id,
        title: "Submission Status Update ⚠️",
        message: "Your submission 'Crypto Trading Signals Discord Mod & Promoter' was rejected by moderators due to community guideline violations.",
        type: "REJECTION",
        link: "/dashboard/submissions",
        isRead: false,
      },
    ],
  });

  console.log("✅ Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
